### ISSUE TITLE
상단 바꾸면 좋을듯?

### ISSUE THREAD

**Issue by xpmxf4** [khmgobe/khmgobe#1]
- 상단 nav 바 깔끔한데, 뭔가 심심함
- 사람들이 너무 많이하는 디자인임 -> 나도 바꿀 예정 
- 커피 좋아하니까, 차라리 `에스프레소 한잔 같은 개발자, 김형민입니다` 에다가
- 커피 사진 박으면 어떨까 싶음

- 아니면 그냥 담백하게, 아래처럼 하는 게 나을수도 있음
- 괜시리 화려하게 하다, 담백보다 못할 수도?
<img width="2238" alt="스크린샷 2024-07-08 오후 5 30 53" src="https://github.com/khmgobe/khmgobe/assets/68197907/3737bd99-fcf6-4692-90eb-cdbfd3ae2b49"
href="https://github.com/yoosion030">
- 사진에 링크 걸어둠

**Comment by featureofme** [comment]
여기에 댓글 달릴 수 있는지 몰랐네 ㅋㅋㅋ
한번 확인해볼게 😁
